# Generated by Django 3.2.6 on 2022-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, '收藏'), (1, '后端'), (2, '项目相关')], null=True, verbose_name='文章分类'),
        ),
    ]
