# Generated by Django 3.2.6 on 2022-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='文章密码'),
        ),
    ]
