# Generated by Django 3.2.6 on 2022-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_articles_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='文章链接'),
        ),
    ]
