# Generated by Django 4.1.2 on 2023-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_articles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='word',
            field=models.IntegerField(default=0, verbose_name='文章字数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '前端'), (2, '后端'), (3, '项目相关')], null=True, verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
